name: Ensure source code is properly formatted

on:
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run fmt
        run: make fmt

      - name: Run generate
        run: make generate

      - name: Check for changes
        run: git diff --exit-code



